[build]
  command = "dotnet publish -c Release -o ./publish"
  publish = "publish/wwwroot"

[build.environment]
  DOTNET_VERSION = "8.0"
  DOTNET_NOLOGO = "true"
  DOTNET_CLI_TELEMETRY_OPTOUT = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
